{% set name = "fonttools" %}
{% set version = "4.60.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 520d2c993ffd386716441d19a1ca65020c54741ceb771c2d2a2557156c12010d

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - fonttools = fontTools.__main__:main
    - ttx = fontTools.ttx:main
    - pyftsubset = fontTools.subset:main
    - pyftmerge = fontTools.merge:main
  script_env:
    - FONTTOOLS_WITH_CYTHON=1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - setuptools
  run:
    - python
    - brotli-python >=1.0.1
    - unicodedata2 >=15.1.0  # [py<313]
  run_constrained:
    - fs >=2.2.0,<3  # extra:ufo
    - lxml >=4.0
    - zopfli >=0.1.4
    - lz4 >=1.7.4.2
    - skia-pathops >=0.5.0
    - uharfbuzz >=0.23.0

test:
  source_files:
    - Tests
  imports:
    - fontTools
    - fontTools.ttLib
    - fontTools.cffLib
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - fonttools subset --help
    - ttx -h
    - pyftsubset --help
    - echo $FONTTOOLS_WITH_CYTHON
    - python -c "from fontTools.cu2qu.cu2qu import COMPILED; assert COMPILED"
    - pytest
    # pyftmerge has no help option
    # pyftinspect requires gtk

about:
  home: https://github.com/fonttools/fonttools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fontTools is a library for manipulating fonts, written in Python.
  description: |
    fontTools is a library for manipulating fonts, written in Python. The
    project includes the TTX tool, that can convert TrueType and OpenType
    fonts to and from an XML text format, which is also called TTX. It
    supports TrueType, OpenType, AFM and to an extent Type 1 and some
    Mac-specific formats. The project has a BSD-style open-source license.
  doc_url: https://fonttools.readthedocs.io
  dev_url: https://github.com/fonttools/fonttools

extra:
  recipe-maintainers:
    - CJ-Wright
