travis:
  secure:
    BINSTAR_TOKEN: GI5Z9gec6yn+INQ9NC8w5PPvj/GYJDuYYMKNsQS0PEDmUBD6oIhRvjlfCNpn4pGcwON6ffT2G5S/Q3NAidnNeQ3XaNcXEHUmFNvdJb8VrFjdSnELmazGuvt877ZmlXaEuhzuRd6uO/A5sGUSMNw8vxwGjyo2qSh/Y6oX/57LPEbXrpg/Vi+Fe2cddSEQzV3FqPMGjta3YSFm2Q8gNsNi5TWft9nEec7FhkYrVg6Y7QUpHHOKFHdKJ3O+lAQOdM5+4PGPI3Qv4RTP+8smNe53uYMiEKO4NQ2PbAqrhkeKVORBoVWdDuN5J0BDaupKfI7KfTg4aCV+ORHKdM6XkPsuYj+ms0vJFC2mPhcKQrjCD8/Y3KjNv2cjjvcreyuKXFvhd1fnou+OuFRjEKAdPhLUyyELXf1ikw6ge054/tK+dkhkfBPtULBIIEZ+Cjxj+J0Xc04clKMUaCWMf9DkJB/1i1Ns4QP3Y9ziIhxQEIedhQSh72FTF3NpwZLls+KCXMvMD7yHbMvfBSr/svcFy/fvNTWkcEpRCFHh/94y49KJw6dzq/k0x1K1t1cZoJ8fsfLFztr7I1j1APj9PVhpuQy9hM0NgYKHZUVjOmT6vyhhg19Kv8kbb8uRBLsxVL91rrnp43gRaAsPT9rksq3oqhTW7Huz+kwjaw6IC0s1R6CxCpQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
